name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          extra_system_packages: "inkscape"
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          continue_on_error: true
          texlive_version: 2024
          working_directory: Projekt/docs
          root_file: Sprawozdanie.tex
      - name: Copy
        run: |
          mdkir tikz
          mkdir out
          cp ./Projekt/docs/Sprawozdanie.pdf ./out/Sprawozdanie.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Sprawozdanie
          path: ./out/Sprawozdanie.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./out/Sprawozdanie.pdf