name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Projekt/docs/Sprawozdanie.tex
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
        env: |
          BIBINPUTS=Projekt/docs/
          BSTINPUTS=Projekt/docs/
          TEXINPUTS=Projekt/docs/:Projekt/docs/sections/:Projekt/docs/figures/
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Sprawozdanie.pdf