name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
          continue_on_error: true
          texlive_version: 2024
          working_directory: Projekt/docs
          root_file: Sprawozdanie.tex      
        env:
          TEXINPUTS: .:Projekt/docs/:Projekt/docs/sections/:Projekt/docs/figures/
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Sprawozdanie.pdf