name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Download custom template
        run: |
          curl -OL https://example.com/custom_template.zip
          unzip custom_template.zip
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: Sprawozdanie.tex
          latexmk_shell_escape: true
          latexmk_use_lualatex: true
        env:
          TEXINPUTS: TEXINPUTS=Projekt/docs/:Projekt/docs/sections/:Projekt/docs/figures/
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Sprawozdanie.pdf